"""
Tutor Workflows for Educational Interactions

Workflows that orchestrate tutor agents with handoff-based routing for educational interactions.
This demonstrates the agent handoff pattern where a triage agent delegates to specialized tutors.
"""

import os
from agnt5 import workflow, WorkflowContext
from entities import TutorConversation
from agents import tutor_agent


@workflow
async def tutor_chat_workflow(ctx: WorkflowContext, message: str, session_id: str = None) -> dict:
    """
    Simple chat-based tutor workflow that maintains conversation history.

    This workflow demonstrates:
    - Session-based conversation tracking via Entity pattern
    - State management across multiple workflow executions
    - Subject detection and routing
    
    Args:
        message: Student's message/question
        session_id: Session identifier (auto-generated by platform if not provided)
    """
    ctx.logger.info(f"Tutor chat workflow - session_id: {session_id}, message: {message}")

    # Instantiate entity for this session (auto-loads state if exists)
    conversation = TutorConversation(key=f"tutor_session:{session_id}")

    # Add user message to conversation history
    await conversation.add_message("user", message)

    # Get current conversation state
    messages = await conversation.get_messages()
    primary_subject = await conversation.get_primary_subject()
    message_count = await conversation.get_message_count()

    # Simple subject detection from first user message
    if primary_subject == "general" and message_count == 1:
        detected_subject = "general"
        message_lower = message.lower()
        
        if any(word in message_lower for word in ["history", "historical", "war", "revolution", "empire", "ancient", "medieval"]):
            detected_subject = "history"
        elif any(word in message_lower for word in ["math", "mathematics", "calculate", "equation", "solve", "algebra", "geometry"]):
            detected_subject = "math"
        
        await conversation.set_primary_subject(detected_subject)
        primary_subject = detected_subject

    # Use the triage agent which will hand off to specialized tutors
    try:
        # Get recent conversation context for the agent
        recent_messages = await conversation.get_recent_messages(5)
        context_str = ""
        if len(recent_messages) > 1:  # If there's conversation history
            context_str = f"\n\nConversation context (recent messages):\n"
            for msg in recent_messages[:-1]:  # Exclude current message
                context_str += f"{msg['role']}: {msg['content']}\n"

        # Create input for the triage agent with context
        agent_input = f"Subject area: {primary_subject}\nStudent question: {message}{context_str}"

        # The triage agent will automatically hand off to specialized tutors (history/math)
        result = await tutor_agent.run_sync(agent_input, context=ctx)
        response = result.output
        
    except Exception as e:
        ctx.logger.error(f"Error running tutor agent: {e}")
        # Fallback response
        response = f"I apologize, but I'm having trouble processing your question right now. Could you please rephrase: {message}"

    # Add assistant response to conversation history
    await conversation.add_message("assistant", response, primary_subject)

    ctx.logger.info(f"Updated conversation: {message_count} messages, subject: {primary_subject}")

    return {
        "output": response,
        "session_id": session_id,
        "message_count": message_count,
        "subject": primary_subject,
        "conversation_preview": (await conversation.get_recent_messages(3))
    }

__all__ = [
    "tutor_chat_workflow",
    "simple_tutor_workflow",
]